# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfa5202bb6bbed434b6e410541195df161f600e6c9be7f5ff35c75964ca21c5545a08fefdee262c274590b36c4e6bf4e8a3563ad9683180d7949071fc529f519

test:
  secret_key_base: e2ae4fafd8da21a7eb9e0dd214504fad541b8f45c14f11957e688a0fe7b53cf9dc6523606090308257b6c3eef32f5c573051427c51efe93ad82009c6f95cbbcd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
